name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check linting
        run: npm run lint

      - name: Check types
        run: npm run check-types

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
          working-directory: ./ #optional
          options: #optional

      - name: Build extension
        run: npm run package
